import type { Metadata } from "next";
import { Inter } from "next/font/google";

// https://stackoverflow.com/questions/74573236/pass-props-to-page-jsx-child-from-root-layout-next-js-13

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: any) {
  props.params.testing = "something";
  console.log("props.params from Root Layout", props.params);
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>My Site</h1>
        <p>props.params from Root Layout: {JSON.stringify(props.params)}</p>
        {props.children}
      </body>
    </html>
  );
}
